// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: utils.sql

package database

import (
	"context"
)

const resetDatabase = `-- name: ResetDatabase :exec
SELECT reset_database()
`

func (q *Queries) ResetDatabase(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetDatabase)
	return err
}
